---

- name: docker image pre-pull
  command: docker pull {{ docker_image }}
  when: use_dockerspawner

- name: load jupyterhub supervisor config
  supervisorctl: name=jupyterhub state=present

- name: restart jupyterhub with supervisor
  supervisorctl: name=jupyterhub state=restarted
